### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by chenrui333**
Relates to https://github.com/Homebrew/homebrew-core/pull/46182

### CODE REVIEW

**Comment by chenrui333** [comment]
Also looks like `set_nofile` function is never used:

```
warning: function is never used: `set_nofile`
   --> src/main.rs:166:1
    |
166 | fn set_nofile(config: &Config) -> Result<()> {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
```

**Comment by chenrui333** [comment]
looks like the mac build got fixed but linux builds failed.

**Comment by kpcyrd** [comment]
Applied in #73 and #74

**Comment by chenrui333** [comment]
Thanks!

**Pull request closed without merging**
